[packages]
libvips = "libvips"
nodejs = "18"
npm = "9"

[context.production.environment]
PORT = "8080"

[build]
nixpacks_version = "1.32.0"
builder = "nixpacks"

[phases.setup]
nixPkgs = ["nodejs_18", "openssl", "python3"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "8080" 