[build]
builder = "nixpacks"
buildCommand = "npm cache clean --force && npm install --omit=dev --no-audit --no-fund && chmod +x migrate.sh && ./migrate.sh && npm run build"

[deploy]
startCommand = "PORT=8080 node .next/standalone/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
port = 8080
autoDeploy = true

[deploy.env]
NODE_ENV = "production"
# Railway automáticamente inyecta estas variables
# DATABASE_URL ya está configurada por Railway
NEXTAUTH_URL = "https://${RAILWAY_STATIC_URL}"
NEXTAUTH_SECRET = "${NEXTAUTH_SECRET}" 